rails project/english-for-kid-rails-app/english_is_fun/config/routes.rb
Rails.application.routes.draw do
  resources :study_subjects

end

rails project/english-for-kid-rails-app/english_is_fun/app/models/pronunciation.rb
class Pronunciation < ActiveRecord::Base
end

rails project/english-for-kid-rails-app/english_is_fun/app/models/study_subject.rb
class StudySubject < ActiveRecord::Base
end

rails project/english-for-kid-rails-app/english_is_fun/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails project/english-for-kid-rails-app/english_is_fun/app/controllers/study_subjects_controller.rb
class StudySubjectsController < ApplicationController
  before_action :set_study_subject, only: [:show, :edit, :update, :destroy]

  # GET /study_subjects
  # GET /study_subjects.json
  def index
    @study_subjects = StudySubject.all
  end

  # GET /study_subjects/1
  # GET /study_subjects/1.json
  def show
  end

  # GET /study_subjects/new
  def new
    @study_subject = StudySubject.new
  end

  # GET /study_subjects/1/edit
  def edit
  end

  # POST /study_subjects
  # POST /study_subjects.json
  def create
    @study_subject = StudySubject.new(study_subject_params)

    respond_to do |format|
      if @study_subject.save
        format.html { redirect_to @study_subject, notice: 'Study subject was successfully created.' }
        format.json { render :show, status: :created, location: @study_subject }
      else
        format.html { render :new }
        format.json { render json: @study_subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /study_subjects/1
  # PATCH/PUT /study_subjects/1.json
  def update
    respond_to do |format|
      if @study_subject.update(study_subject_params)
        format.html { redirect_to @study_subject, notice: 'Study subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @study_subject }
      else
        format.html { render :edit }
        format.json { render json: @study_subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /study_subjects/1
  # DELETE /study_subjects/1.json
  def destroy
    @study_subject.destroy
    respond_to do |format|
      format.html { redirect_to study_subjects_url, notice: 'Study subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study_subject
      @study_subject = StudySubject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_subject_params
      params.require(:study_subject).permit(:title)
    end
end

rails project/english-for-kid-rails-app/english_is_fun/app/helpers/application_helper.rb
module ApplicationHelper
end

rails project/english-for-kid-rails-app/english_is_fun/app/helpers/study_subjects_helper.rb
module StudySubjectsHelper
end

rails project/english-for-kid-rails-app/english_is_fun/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnglishIsFun</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rails project/english-for-kid-rails-app/english_is_fun/app/views/study_subjects/_form.html.erb
<%= form_for(@study_subject) do |f| %>
  <% if @study_subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study_subject.errors.count, "error") %> prohibited this study_subject from being saved:</h2>

      <ul>
      <% @study_subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails project/english-for-kid-rails-app/english_is_fun/app/views/study_subjects/edit.html.erb
<h1>Editing Study Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @study_subject %> |
<%= link_to 'Back', study_subjects_path %>

rails project/english-for-kid-rails-app/english_is_fun/app/views/study_subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Study Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @study_subjects.each do |study_subject| %>
      <tr>
        <td><%= study_subject.title %></td>
        <td><%= link_to 'Show', study_subject %></td>
        <td><%= link_to 'Edit', edit_study_subject_path(study_subject) %></td>
        <td><%= link_to 'Destroy', study_subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Study subject', new_study_subject_path %>

rails project/english-for-kid-rails-app/english_is_fun/app/views/study_subjects/new.html.erb
<h1>New Study Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', study_subjects_path %>

rails project/english-for-kid-rails-app/english_is_fun/app/views/study_subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @study_subject.title %>
</p>

<%= link_to 'Edit', edit_study_subject_path(@study_subject) %> |
<%= link_to 'Back', study_subjects_path %>