thanh/thanht4/config/routes.rb
Rails.application.routes.draw do
  resources :pronunciations

  get ':controller(/:action(/:id(.:format)))'

end

thanh/thanht4/app/models/pronunciation.rb
class Pronunciation < ActiveRecord::Base
end

thanh/thanht4/app/models/th.rb
class Th < ActiveRecord::Base
end

thanh/thanht4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

thanh/thanht4/app/controllers/pronunciations_controller.rb
class PronunciationsController < ApplicationController
  before_action :set_pronunciation, only: [:show, :edit, :update, :destroy]

  # GET /pronunciations
  # GET /pronunciations.json
  def index
    @pronunciations = Pronunciation.all
  end

  # GET /pronunciations/1
  # GET /pronunciations/1.json
  def show
  end

  # GET /pronunciations/new
  def new
    @pronunciation = Pronunciation.new
  end

  # GET /pronunciations/1/edit
  def edit
  end

  # POST /pronunciations
  # POST /pronunciations.json
  def create
    @pronunciation = Pronunciation.new(pronunciation_params)

    respond_to do |format|
      if @pronunciation.save
        format.html { redirect_to @pronunciation, notice: 'Pronunciation was successfully created.' }
        format.json { render :show, status: :created, location: @pronunciation }
      else
        format.html { render :new }
        format.json { render json: @pronunciation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pronunciations/1
  # PATCH/PUT /pronunciations/1.json
  def update
    respond_to do |format|
      if @pronunciation.update(pronunciation_params)
        format.html { redirect_to @pronunciation, notice: 'Pronunciation was successfully updated.' }
        format.json { render :show, status: :ok, location: @pronunciation }
      else
        format.html { render :edit }
        format.json { render json: @pronunciation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pronunciations/1
  # DELETE /pronunciations/1.json
  def destroy
    @pronunciation.destroy
    respond_to do |format|
      format.html { redirect_to pronunciations_url, notice: 'Pronunciation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pronunciation
      @pronunciation = Pronunciation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pronunciation_params
      params.require(:pronunciation).permit(:title)
    end
end

thanh/thanht4/app/controllers/tth_controller.rb
class TthController < ApplicationController
end

thanh/thanht4/app/helpers/application_helper.rb
module ApplicationHelper
end

thanh/thanht4/app/helpers/pronunciations_helper.rb
module PronunciationsHelper
end

thanh/thanht4/app/helpers/tth_helper.rb
module TthHelper
end

thanh/thanht4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thanht4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

thanh/thanht4/app/views/pronunciations/_form.html.erb
<%= form_for(@pronunciation) do |f| %>
  <% if @pronunciation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pronunciation.errors.count, "error") %> prohibited this pronunciation from being saved:</h2>

      <ul>
      <% @pronunciation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

thanh/thanht4/app/views/pronunciations/edit.html.erb
<h1>Editing Pronunciation</h1>

<%= render 'form' %>

<%= link_to 'Show', @pronunciation %> |
<%= link_to 'Back', pronunciations_path %>

thanh/thanht4/app/views/pronunciations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pronunciations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pronunciations.each do |pronunciation| %>
      <tr>
        <td><%= pronunciation.title %></td>
        <td><%= link_to 'Show', pronunciation %></td>
        <td><%= link_to 'Edit', edit_pronunciation_path(pronunciation) %></td>
        <td><%= link_to 'Destroy', pronunciation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pronunciation', new_pronunciation_path %>

thanh/thanht4/app/views/pronunciations/new.html.erb
<h1>New Pronunciation</h1>

<%= render 'form' %>

<%= link_to 'Back', pronunciations_path %>

thanh/thanht4/app/views/pronunciations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pronunciation.title %>
</p>

<%= link_to 'Edit', edit_pronunciation_path(@pronunciation) %> |
<%= link_to 'Back', pronunciations_path %>